# Generated by Django 4.2.4 on 2023-08-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1997-02-21'),
            preserve_default=False,
        ),
    ]
